[package]
name = "game"
version = "0.1.0"
edition = "2021"

[dependencies]
common = { path = "../common"}
bevy = { version = "0.16.1", features = ["dynamic_linking"] }
bevy_panorbit_camera = "0.26.0"
ron = "0.10.1"
serde = { version = "1.0.219", features = ["derive"] }
thiserror = "2.0.12"
