[package]
name = "common"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { version = "0.16.1", default-features = false }
ron = "0.10.1"
serde = { version = "1.0.219", features = ["derive"] }
thiserror = "2.0.12"
